name: OpenAPI Client Generator
run-name: OpenAPI Client Generator Github Action 🚀
on: [push]
jobs:
  generate-java-client:
    name: Generate Java Client
    runs-on: ubuntu-latest
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Java Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          openapi-file: openapi.yaml
          generator: java
          config-file: generator-config-java.yaml

      # see: https://github.com/marketplace/actions/zip-release
      - name: Zip Generated Client Sources
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          path: 'java-client'
          filename: 'java-client-sources.zip'
          exclusions: '/*node_modules/* .editorconfig'

      # see: https://github.com/actions/upload-artifact
      - name: Upload Generated Java Client Sources
        uses: actions/upload-artifact@v4
        with:
          name: java-client-sources
          path: java-client-sources.zip

  generate-documentation:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate OpenAPI Documentation
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          openapi-file: openapi.yaml
          generator: html2
      
      # see: https://github.com/marketplace/actions/zip-release
      - name: Zip Generated Documentation
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          path: 'html2-client'
          filename: 'api-documentation.zip'
          exclusions: '/*node_modules/* .editorconfig'

      # see: https://github.com/actions/upload-artifact
      - name: Upload Zipped Documentation
        uses: actions/upload-artifact@v4
        with:
          name: api-documentation
          path: api-documentation.zip

  build-generated-java-client-sources:
    name: Build Java Client Library.
    runs-on: ubuntu-latest
    needs:
      - generate-java-client
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-client-sources
          path: downloaded-artifacts

      - name: Unzip Java Client Sources
        run: unzip downloaded-artifacts/java-client-sources.zip

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: sapmachine # see: https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
          #cache: maven
          #cache-dependency-path: ${{github.workspace}}/java-client/pom.xml
      
      - name: Build with Maven
        run: mvn -B clean package --no-transfer-progress --file java-client/pom.xml
      
      # see: https://github.com/actions/upload-artifact
      - name: Upload Java Client Library
        uses: actions/upload-artifact@v4
        with:
          name: java-client-build-artifacts
          path: java-client/target/*.jar

  create-release:
    name: Create New Release
    runs-on: ubuntu-latest
    needs: 
      - generate-java-client
      - build-generated-java-client-sources
      - generate-documentation
    steps:
      # see: https://github.com/actions/download-artifact
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts
      
      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: build-${{ github.run_number }}
          release_name: Release-#${{ github.run_number }}

      - name: Release API Documentation 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: downloaded-artifacts/api-documentation/api-documentation.zip
          asset_name: api-documentation.zip
          asset_content_type: application/zip
      
      - name: Release Java Client Library 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: downloaded-artifacts/java-client-build-artifacts/books-client-api-1.0.0.jar
          asset_name: books-client-api-1.0.0.jar
          asset_content_type: application/jar
      
      - name: Release Java Client Tests 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: downloaded-artifacts/java-client-build-artifacts/books-client-api-1.0.0-tests.jar
          asset_name: books-client-api-1.0.0-tests.jar
          asset_content_type: application/jar
      
      - name: Release Java Client Sources 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: downloaded-artifacts/java-client-build-artifacts/books-client-api-1.0.0-sources.jar
          asset_name: books-client-api-1.0.0-sources.jar
          asset_content_type: application/jar

      - name: Release Java Client Javadoc 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: downloaded-artifacts/java-client-build-artifacts/books-client-api-1.0.0-javadoc.jar
          asset_name: books-client-api-1.0.0-javadoc.jar
          asset_content_type: application/jar

      - name: Release Java Client Sources Zip 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: downloaded-artifacts/java-client-sources/java-client-sources.zip
          asset_name: java-client-sources.zip
          asset_content_type: application/zip

