name: OpenAPI Client Generator
run-name: OpenAPI Client Generator Github Action 🚀
on: [push]
jobs:
  generate-java-client:
    runs-on: ubuntu-latest
    name: Generate Java Client
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Java Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          openapi-file: openapi.yaml
          generator: java
          config-file: generator-config-java.yaml

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: sapmachine # see: https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
          #cache: maven
          #cache-dependency-path: ${{github.workspace}}/java-client/pom.xml

      - name: Build with Maven
        run: mvn -B clean package --no-transfer-progress --file java-client/pom.xml

  generate-documentation:
    runs-on: ubuntu-latest
    name: Generate API Documentation
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate OpenAPI Documentation
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          openapi-file: openapi.yaml
          generator: html2

  # release-java-client-lib:
  #   runs-on: ubuntu-latest
  #   name: Release Java Client Library
  #   needs: generate-java-client       # wait for generate-java-client job to have finished.
  #   steps:
  #     - name: Set up JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: 21
  #         distribution: sapmachine # see: https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
  #         #cache: maven
  #         #cache-dependency-path: ${{github.workspace}}/java-client/pom.xml

  #     - name: Build with Maven
  #       run: mvn -B clean package --no-transfer-progress --file java-client/pom.xml
